"""
Export cookies + localStorage from a profile's persistent user_data_dir.

Opens a short-lived headless Camoufox session on the profile's persistent
storage, reads the browser context, writes:

  - JSON (all cookies + per-domain localStorage/sessionStorage)
  - Netscape cookies.txt (for import into other browsers / curl)
  - Chromium-compatible cookies.json (for Puppeteer / Playwright imports)

Used for the manual "cookie handoff" workflow — when a Queue-it session
reaches position ~50, export its state, send via webhook, let a human
import it in their own browser to complete the checkout.
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional


def export_profile_cookies(
    profile_id: str,
    visit_urls: Optional[List[str]] = None,
    output_dir: Optional[str] = None,
) -> Dict[str, Any]:
    """Launch a short headless session on the profile's user_data_dir, read
    cookies + storage, shut down. Writes 3 files and returns a summary.

    `visit_urls` - if given, navigate to each and read localStorage from
    that origin (cross-origin storage isn't accessible otherwise).
    """
    import fpgen
    from camoufox.sync_api import Camoufox  # lazy

    store = fpgen.ProfileStore(
        os.environ.get("FPGEN_STORE", str(Path.home() / ".camoufox" / "fpgen"))
    )
    profile = store.load(profile_id)
    config = fpgen.to_camoufox_config(profile)

    user_data_dir = Path.home() / ".camoufox" / "launcher" / "user_data" / profile_id
    user_data_dir.mkdir(parents=True, exist_ok=True)

    output_dir_p = Path(output_dir) if output_dir else (
        Path.home() / ".camoufox" / "launcher" / "exports"
    )
    output_dir_p.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    base = output_dir_p / f"{profile_id}-{ts}"

    cookies: List[Dict[str, Any]] = []
    local_storage: Dict[str, Dict[str, str]] = {}
    session_storage: Dict[str, Dict[str, str]] = {}

    with Camoufox(
        config=config,
        headless=True,
        persistent_context=True,
        user_data_dir=str(user_data_dir),
    ) as ctx:
        cookies = ctx.cookies()
        # localStorage is per-origin. If the caller passed visit_urls, visit
        # each and read. Otherwise derive candidate origins from the cookie
        # domains.
        origins = set(visit_urls or [])
        for c in cookies:
            dom = c.get("domain", "").lstrip(".")
            if dom:
                origins.add(f"https://{dom}/")
        # Only keep reasonably-likely ones to avoid slow mass-visits.
        origins = set(list(origins)[:20])
        page = ctx.new_page()
        for origin in origins:
            try:
                page.goto(origin, timeout=8_000, wait_until="domcontentloaded")
                ls = page.evaluate(
                    "() => Object.fromEntries(Object.entries(localStorage))"
                )
                ss = page.evaluate(
                    "() => Object.fromEntries(Object.entries(sessionStorage))"
                )
                if ls:
                    local_storage[origin] = ls
                if ss:
                    session_storage[origin] = ss
            except Exception:  # noqa: BLE001
                continue

    # --- write files ---
    full = {
        "export_version": 1,
        "profile_id": profile_id,
        "profile_name": profile.name,
        "exported_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "cookies": cookies,
        "local_storage": local_storage,
        "session_storage": session_storage,
    }
    (base.with_suffix(".json")).write_text(json.dumps(full, indent=2, default=str))
    _write_netscape(base.with_suffix(".txt"), cookies)

    return {
        "profile_id": profile_id,
        "cookie_count": len(cookies),
        "storage_origins": len(local_storage),
        "files": {
            "json": str(base.with_suffix(".json")),
            "netscape": str(base.with_suffix(".txt")),
        },
    }


def _write_netscape(path: Path, cookies: List[Dict[str, Any]]) -> None:
    """Emit a Netscape cookies.txt file (used by curl, wget, Puppeteer imports)."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by camoufox-launcher export-cookies",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", "")
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path_ = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = int(c.get("expires") or 0)
        if expires < 0:
            expires = 0
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append("\t".join([
            domain, include_subdomains, path_, secure, str(expires), name, value,
        ]))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def post_export_to_webhook(export_result: Dict[str, Any], url: Optional[str] = None) -> bool:
    """Upload the exported JSON to a webhook (Discord supports 8MB attachments,
    or any HTTP POST endpoint). Useful for the handoff workflow: human reads
    the cookies in their own machine within seconds of the trigger.
    """
    from launcher.bridge.webhook import get_webhook
    import requests

    hook = url or get_webhook()
    if not hook:
        return False
    json_file = export_result["files"]["json"]
    try:
        with open(json_file, "rb") as f:
            r = requests.post(
                hook,
                data={
                    "content": (
                        f"🍪 Cookies exportés — profil `{export_result['profile_id']}` — "
                        f"{export_result['cookie_count']} cookies"
                    )
                },
                files={"file": (Path(json_file).name, f, "application/json")},
                timeout=15.0,
            )
            return 200 <= r.status_code < 300
    except Exception:  # noqa: BLE001
        return False
